// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/gvillela7/rank-my-app/configs"
	"github.com/gvillela7/rank-my-app/internal/adapter/messages/consumers"
	mongo3 "github.com/gvillela7/rank-my-app/internal/adapter/repository/mongo"
	"github.com/gvillela7/rank-my-app/internal/core/ports"
	"github.com/gvillela7/rank-my-app/internal/core/usecase"
	"github.com/gvillela7/rank-my-app/internal/infra/database/mongo"
	"github.com/gvillela7/rank-my-app/internal/infra/rabbitmq"
	mongo2 "go.mongodb.org/mongo-driver/mongo"
	"go.uber.org/zap"
	"strconv"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*App, func(), error) {
	logger, err := ProvideLogger()
	if err != nil {
		return nil, nil, err
	}
	rabbitMQConnection, err := ProvideRabbitMQConnection(logger)
	if err != nil {
		return nil, nil, err
	}
	mongoDBConnection, err := ProvideMongoConnection(ctx)
	if err != nil {
		return nil, nil, err
	}
	database, err := ProvideMongoDatabase(mongoDBConnection)
	if err != nil {
		return nil, nil, err
	}
	orderRepository := ProvideOrderRepository(database, logger)
	publishedOrderRepository := ProvidePublishedOrderRepository(database, logger)
	orderUseCase := ProvideOrderUseCase(orderRepository, publishedOrderRepository, logger)
	messageConsumer := ProvideMessageConsumer(rabbitMQConnection, orderUseCase, logger)
	app := ProvideApp(messageConsumer, mongoDBConnection, rabbitMQConnection, logger)
	return app, func() {
	}, nil
}

// wire.go:

type App struct {
	Consumer     ports.MessageConsumer
	DB           *mongo.MongoDBConnection
	RabbitMQConn *rabbitmq.RabbitMQConnection
	Logger       *zap.Logger
}

func ProvideApp(
	consumer ports.MessageConsumer,
	conn *mongo.MongoDBConnection,
	rabbitConn *rabbitmq.RabbitMQConnection,
	logger *zap.Logger,
) *App {
	return &App{
		Consumer:     consumer,
		DB:           conn,
		RabbitMQConn: rabbitConn,
		Logger:       logger,
	}
}

func ProvideMongoConnection(ctx context.Context) (*mongo.MongoDBConnection, error) {
	return mongo.NewMongoDBConnection(ctx)
}

func ProvideMongoDatabase(conn *mongo.MongoDBConnection) (*mongo2.Database, error) {
	return conn.Client()
}

func ProvideLogger() (*zap.Logger, error) {
	return zap.NewProduction()
}

func ProvideOrderRepository(db *mongo2.Database, logger *zap.Logger) ports.OrderRepository {
	return mongo3.NewOrderRepository(db, logger)
}

func ProvideOrderUseCase(
	repo ports.OrderRepository,
	publishedOrderRepo ports.PublishedOrderRepository,
	logger *zap.Logger,
) ports.OrderUseCase {
	return usecase.NewOrderUseCase(repo, publishedOrderRepo, logger)
}

func ProvideRabbitMQConnection(logger *zap.Logger) (*rabbitmq.RabbitMQConnection, error) {
	cfg := config.GetRabbitMQConfig()

	logger.Info("Loading RabbitMQ configuration", zap.String("host", cfg.Host), zap.String("port", cfg.Port), zap.String("username", cfg.Username), zap.String("vhost", cfg.VHost))

	port, err := strconv.Atoi(cfg.Port)
	if err != nil {
		logger.Error("Invalid RabbitMQ port configuration", zap.String("port", cfg.Port), zap.Error(err))
		port = 5672
	}

	return rabbitmq.NewRabbitMQConnection(
		cfg.Host,
		port,
		cfg.Username,
		cfg.Password,
		cfg.VHost,
		logger,
	)
}

func ProvidePublishedOrderRepository(db *mongo2.Database, logger *zap.Logger) ports.PublishedOrderRepository {
	return mongo3.NewPublishedOrderRepository(db, logger)
}

func ProvideMessageConsumer(
	rabbitConn *rabbitmq.RabbitMQConnection,
	useCase ports.OrderUseCase,
	logger *zap.Logger,
) ports.MessageConsumer {
	return consumers.NewOrderConsumer(rabbitConn, useCase, logger)
}
